version: 1

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'

handlers:
  default:
    level: 'DEBUG'
    formatter: 'standard'
    class: 'logging.StreamHandler'

loggers:
  redis:
    handlers:
      - default
    level: 'DEBUG'
